---
########################################################## {tag.top} ###
## IBM Confidential
## OCO Source Materials
## *** siam-msv-core ***
##
## (C) Copyright IBM Corporation 2021
##
## The source code for this program is not published or otherwise
## divested of its trade secrets, irrespective of what has been
## deposited with the U.S. Copyright Office.
########################################################## {tag.end} ###
- hosts: appservers
  sudo: "{{ user_deploy_opts }}"

  roles:
    - install
 
  vars:
    # Define application level variables here

# ------------------------------------------------------------------------------
# END OF SCRIPT.
# ------------------------------------------------------------------------------
   
